# Server Configuration
server.port={cipher}b761accf7348dd0bb5dd717477f715b7488adbe0d7dacdd6537798f6ba422907
server.http.port={cipher}cd83eb54557c5400b274e29ca5d7bc9e61301ce3e6779ae9ac9c6686c06dfe20
server.servlet.context-path=/hr-service/api
server.ssl.enabled=true

# Server keystore
server.ssl.key-store=classpath:spring-server.jks
server.ssl.key-store-password={cipher}7e29e0fcbe4db06a7b17564e1923aac5ec2c6d20477f1226f379f6379dc242e7
server.ssl.key-store-type=JKS
server.ssl.key-alias=spring-server

# Server protocols
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2

# Health check endpoint
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.non-secure-port=${server.http.port}
eureka.instance.secure-port=${server.port}
eureka.instance.secure-port-enabled=true
eureka.instance.home-page-url=https://localhost:${server.port}${server.servlet.context-path}
eureka.instance.status-page-url=https://localhost:${server.port}${server.servlet.context-path}/actuator/info
eureka.instance.health-check-url=https://localhost:${server.port}${server.servlet.context-path}/actuator/health

